CREATE DATABASE MYSALES
CREATE TABLE CLIENTE
(CLIENTE_ID INT,
NOME_CLIENTE VARCHAR (30),
CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_ID));
CREATE TABLE ORDINE
(ORDINE_ID INT,
CLIENTE_ID INT,
CONSTRAINT PK_ORDINE PRIMARY KEY (ORDINE_ID),
CONSTRAINT FK_ORDINE_CLIENTE FOREIGN KEY (CLIENTE_ID)
REFERENCES CLIENTE (CLIENTE_ID));
INSERT INTO CLIENTE (CLIENTE_ID, NOME_CLIENTE)
VALUES (1, 'SERENA'), (2,'SARA'), (3,'SONIA');
INSERT INTO ORDINE (ORDINE_ID,CLIENTE_ID)
VALUES (25, 1), (30, 2), (40, 3)

select * from ORDINE